// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: wallet.proto

package go_mnhosted_srv_wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Wallet service

type WalletService interface {
	New(ctx context.Context, in *NewRequest, opts ...client.CallOption) (*NewResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...client.CallOption) (*GetBalanceResponse, error)
	Pay(ctx context.Context, in *PayRequest, opts ...client.CallOption) (*PayResponse, error)
}

type walletService struct {
	c    client.Client
	name string
}

func NewWalletService(name string, c client.Client) WalletService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.mnhosted.srv.wallet"
	}
	return &walletService{
		c:    c,
		name: name,
	}
}

func (c *walletService) New(ctx context.Context, in *NewRequest, opts ...client.CallOption) (*NewResponse, error) {
	req := c.c.NewRequest(c.name, "Wallet.New", in)
	out := new(NewResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletService) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...client.CallOption) (*GetBalanceResponse, error) {
	req := c.c.NewRequest(c.name, "Wallet.GetBalance", in)
	out := new(GetBalanceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletService) Pay(ctx context.Context, in *PayRequest, opts ...client.CallOption) (*PayResponse, error) {
	req := c.c.NewRequest(c.name, "Wallet.Pay", in)
	out := new(PayResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wallet service

type WalletHandler interface {
	New(context.Context, *NewRequest, *NewResponse) error
	GetBalance(context.Context, *GetBalanceRequest, *GetBalanceResponse) error
	Pay(context.Context, *PayRequest, *PayResponse) error
}

func RegisterWalletHandler(s server.Server, hdlr WalletHandler, opts ...server.HandlerOption) error {
	type wallet interface {
		New(ctx context.Context, in *NewRequest, out *NewResponse) error
		GetBalance(ctx context.Context, in *GetBalanceRequest, out *GetBalanceResponse) error
		Pay(ctx context.Context, in *PayRequest, out *PayResponse) error
	}
	type Wallet struct {
		wallet
	}
	h := &walletHandler{hdlr}
	return s.Handle(s.NewHandler(&Wallet{h}, opts...))
}

type walletHandler struct {
	WalletHandler
}

func (h *walletHandler) New(ctx context.Context, in *NewRequest, out *NewResponse) error {
	return h.WalletHandler.New(ctx, in, out)
}

func (h *walletHandler) GetBalance(ctx context.Context, in *GetBalanceRequest, out *GetBalanceResponse) error {
	return h.WalletHandler.GetBalance(ctx, in, out)
}

func (h *walletHandler) Pay(ctx context.Context, in *PayRequest, out *PayResponse) error {
	return h.WalletHandler.Pay(ctx, in, out)
}
