// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package go_mnhosted_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Coinname             string   `protobuf:"bytes,2,opt,name=coinname,proto3" json:"coinname,omitempty"`
	Timetype             int32    `protobuf:"varint,3,opt,name=timetype,proto3" json:"timetype,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	TxID                 string   `protobuf:"bytes,5,opt,name=txID,proto3" json:"txID,omitempty"`
	IsRenew              int32    `protobuf:"varint,6,opt,name=isRenew,proto3" json:"isRenew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRequest) Reset()         { *m = NewRequest{} }
func (m *NewRequest) String() string { return proto.CompactTextString(m) }
func (*NewRequest) ProtoMessage()    {}
func (*NewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *NewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRequest.Unmarshal(m, b)
}
func (m *NewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRequest.Marshal(b, m, deterministic)
}
func (m *NewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRequest.Merge(m, src)
}
func (m *NewRequest) XXX_Size() int {
	return xxx_messageInfo_NewRequest.Size(m)
}
func (m *NewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRequest proto.InternalMessageInfo

func (m *NewRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *NewRequest) GetCoinname() string {
	if m != nil {
		return m.Coinname
	}
	return ""
}

func (m *NewRequest) GetTimetype() int32 {
	if m != nil {
		return m.Timetype
	}
	return 0
}

func (m *NewRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *NewRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *NewRequest) GetIsRenew() int32 {
	if m != nil {
		return m.IsRenew
	}
	return 0
}

type NewResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	ID                   int64    `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewResponse) Reset()         { *m = NewResponse{} }
func (m *NewResponse) String() string { return proto.CompactTextString(m) }
func (*NewResponse) ProtoMessage()    {}
func (*NewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *NewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewResponse.Unmarshal(m, b)
}
func (m *NewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewResponse.Marshal(b, m, deterministic)
}
func (m *NewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewResponse.Merge(m, src)
}
func (m *NewResponse) XXX_Size() int {
	return xxx_messageInfo_NewResponse.Size(m)
}
func (m *NewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewResponse proto.InternalMessageInfo

func (m *NewResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *NewResponse) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type AlipayRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CoinName             string   `protobuf:"bytes,2,opt,name=coinName,proto3" json:"coinName,omitempty"`
	MNKey                string   `protobuf:"bytes,3,opt,name=MNKey,proto3" json:"MNKey,omitempty"`
	TimeType             int32    `protobuf:"varint,4,opt,name=timeType,proto3" json:"timeType,omitempty"`
	IsRenew              int32    `protobuf:"varint,5,opt,name=isRenew,proto3" json:"isRenew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlipayRequest) Reset()         { *m = AlipayRequest{} }
func (m *AlipayRequest) String() string { return proto.CompactTextString(m) }
func (*AlipayRequest) ProtoMessage()    {}
func (*AlipayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *AlipayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlipayRequest.Unmarshal(m, b)
}
func (m *AlipayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlipayRequest.Marshal(b, m, deterministic)
}
func (m *AlipayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlipayRequest.Merge(m, src)
}
func (m *AlipayRequest) XXX_Size() int {
	return xxx_messageInfo_AlipayRequest.Size(m)
}
func (m *AlipayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlipayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlipayRequest proto.InternalMessageInfo

func (m *AlipayRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AlipayRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *AlipayRequest) GetMNKey() string {
	if m != nil {
		return m.MNKey
	}
	return ""
}

func (m *AlipayRequest) GetTimeType() int32 {
	if m != nil {
		return m.TimeType
	}
	return 0
}

func (m *AlipayRequest) GetIsRenew() int32 {
	if m != nil {
		return m.IsRenew
	}
	return 0
}

type AlipayResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	PayUrl               string   `protobuf:"bytes,2,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlipayResponse) Reset()         { *m = AlipayResponse{} }
func (m *AlipayResponse) String() string { return proto.CompactTextString(m) }
func (*AlipayResponse) ProtoMessage()    {}
func (*AlipayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *AlipayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlipayResponse.Unmarshal(m, b)
}
func (m *AlipayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlipayResponse.Marshal(b, m, deterministic)
}
func (m *AlipayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlipayResponse.Merge(m, src)
}
func (m *AlipayResponse) XXX_Size() int {
	return xxx_messageInfo_AlipayResponse.Size(m)
}
func (m *AlipayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AlipayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AlipayResponse proto.InternalMessageInfo

func (m *AlipayResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *AlipayResponse) GetPayUrl() string {
	if m != nil {
		return m.PayUrl
	}
	return ""
}

type ConfirmAlipayRequest struct {
	OrderID              int64    `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAlipayRequest) Reset()         { *m = ConfirmAlipayRequest{} }
func (m *ConfirmAlipayRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmAlipayRequest) ProtoMessage()    {}
func (*ConfirmAlipayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *ConfirmAlipayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAlipayRequest.Unmarshal(m, b)
}
func (m *ConfirmAlipayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAlipayRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmAlipayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAlipayRequest.Merge(m, src)
}
func (m *ConfirmAlipayRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmAlipayRequest.Size(m)
}
func (m *ConfirmAlipayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAlipayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAlipayRequest proto.InternalMessageInfo

func (m *ConfirmAlipayRequest) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *ConfirmAlipayRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ConfirmAlipayResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAlipayResponse) Reset()         { *m = ConfirmAlipayResponse{} }
func (m *ConfirmAlipayResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmAlipayResponse) ProtoMessage()    {}
func (*ConfirmAlipayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *ConfirmAlipayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAlipayResponse.Unmarshal(m, b)
}
func (m *ConfirmAlipayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAlipayResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmAlipayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAlipayResponse.Merge(m, src)
}
func (m *ConfirmAlipayResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmAlipayResponse.Size(m)
}
func (m *ConfirmAlipayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAlipayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAlipayResponse proto.InternalMessageInfo

func (m *ConfirmAlipayResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

type UpdateRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MNKey                string   `protobuf:"bytes,2,opt,name=MNKey,proto3" json:"MNKey,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateRequest) GetMNKey() string {
	if m != nil {
		return m.MNKey
	}
	return ""
}

func (m *UpdateRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

type GetInfoRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetInfoResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Payout               float64  `protobuf:"fixed64,3,opt,name=payout,proto3" json:"payout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *GetInfoResponse) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *GetInfoResponse) GetPayout() float64 {
	if m != nil {
		return m.Payout
	}
	return 0
}

func init() {
	proto.RegisterType((*NewRequest)(nil), "go.mnhosted.srv.order.NewRequest")
	proto.RegisterType((*NewResponse)(nil), "go.mnhosted.srv.order.NewResponse")
	proto.RegisterType((*AlipayRequest)(nil), "go.mnhosted.srv.order.AlipayRequest")
	proto.RegisterType((*AlipayResponse)(nil), "go.mnhosted.srv.order.AlipayResponse")
	proto.RegisterType((*ConfirmAlipayRequest)(nil), "go.mnhosted.srv.order.ConfirmAlipayRequest")
	proto.RegisterType((*ConfirmAlipayResponse)(nil), "go.mnhosted.srv.order.ConfirmAlipayResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.mnhosted.srv.order.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.mnhosted.srv.order.UpdateResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "go.mnhosted.srv.order.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "go.mnhosted.srv.order.GetInfoResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x8e, 0x93, 0x40,
	0x14, 0x5e, 0xa0, 0x50, 0xf7, 0x6c, 0x5a, 0xcd, 0x64, 0xb7, 0x21, 0x5c, 0xd5, 0x89, 0x9a, 0x46,
	0x0d, 0x89, 0x7a, 0xe1, 0xb5, 0xda, 0x68, 0x88, 0x59, 0x2e, 0x88, 0x8d, 0x89, 0x77, 0xd8, 0x9e,
	0x55, 0x92, 0xc2, 0xe0, 0xcc, 0x60, 0xed, 0x53, 0xf8, 0x0a, 0xbe, 0x93, 0x2f, 0x64, 0x18, 0x66,
	0x68, 0xd9, 0x2c, 0xd2, 0x3b, 0xbe, 0xcc, 0xc7, 0xe1, 0xfb, 0x39, 0x03, 0x5c, 0x30, 0xbe, 0x41,
	0x1e, 0x96, 0x9c, 0x49, 0x46, 0xae, 0xbe, 0xb1, 0x30, 0x2f, 0xbe, 0x33, 0x21, 0x71, 0x13, 0x0a,
	0xfe, 0x33, 0x54, 0x87, 0xf4, 0x8f, 0x05, 0x10, 0xe3, 0x2e, 0xc1, 0x1f, 0x15, 0x0a, 0x49, 0x66,
	0xe0, 0x55, 0x02, 0x79, 0xb4, 0xf4, 0xad, 0xb9, 0xb5, 0x70, 0x12, 0x8d, 0x48, 0x00, 0xf7, 0xd6,
	0x2c, 0x2b, 0x8a, 0x34, 0x47, 0xdf, 0x9e, 0x5b, 0x8b, 0xf3, 0xa4, 0xc5, 0xf5, 0x99, 0xcc, 0x72,
	0x94, 0xfb, 0x12, 0x7d, 0x67, 0x6e, 0x2d, 0xdc, 0xa4, 0xc5, 0xe4, 0x12, 0xdc, 0x92, 0x67, 0x6b,
	0xf4, 0x47, 0xea, 0xa0, 0x01, 0x84, 0xc0, 0x48, 0xfe, 0x8a, 0x96, 0xbe, 0xab, 0x26, 0xa9, 0x67,
	0xe2, 0xc3, 0x38, 0x13, 0x09, 0x16, 0xb8, 0xf3, 0x3d, 0xc5, 0x35, 0x90, 0xbe, 0x86, 0x0b, 0xa5,
	0x50, 0x94, 0xac, 0x10, 0x58, 0x13, 0x39, 0x8a, 0x35, 0xdb, 0xa0, 0xd2, 0xe8, 0x26, 0x06, 0x92,
	0x29, 0xd8, 0xd1, 0x52, 0xc9, 0x73, 0x12, 0x3b, 0x5a, 0xd2, 0xdf, 0x16, 0x4c, 0xde, 0x6c, 0xb3,
	0x32, 0xdd, 0x9f, 0x68, 0x2f, 0xbe, 0x65, 0xaf, 0xc6, 0xb5, 0x85, 0xeb, 0xf8, 0x23, 0xee, 0x95,
	0xb7, 0xf3, 0xa4, 0x01, 0xc6, 0xf4, 0xa7, 0xda, 0xf4, 0xe8, 0x60, 0xba, 0xc6, 0xc7, 0x56, 0xdc,
	0xae, 0x95, 0xb7, 0x30, 0x35, 0x82, 0x06, 0xdd, 0xcc, 0xc0, 0x2b, 0xd3, 0xfd, 0x8a, 0x6f, 0xb5,
	0x22, 0x8d, 0xe8, 0x7b, 0xb8, 0x7c, 0xc7, 0x8a, 0x9b, 0x8c, 0xe7, 0x5d, 0x6f, 0x3e, 0x8c, 0x55,
	0xa5, 0xad, 0x39, 0x03, 0x0f, 0x25, 0xd8, 0x47, 0x25, 0xd0, 0x17, 0x70, 0x75, 0x6b, 0xce, 0x90,
	0x24, 0x7a, 0x0d, 0x93, 0x55, 0xb9, 0x49, 0x25, 0x9a, 0x6f, 0x36, 0x89, 0x5b, 0x26, 0xf1, 0x43,
	0x56, 0xf6, 0x71, 0x56, 0x33, 0xf0, 0x84, 0x4c, 0x65, 0x25, 0xf4, 0x7a, 0x68, 0x44, 0x9f, 0xc2,
	0xd4, 0x8c, 0x1b, 0xfc, 0xf4, 0x02, 0xa6, 0x1f, 0x50, 0x46, 0xc5, 0x0d, 0x1b, 0xe8, 0x92, 0xae,
	0xe0, 0x7e, 0xcb, 0x1c, 0x0c, 0xf9, 0x01, 0x38, 0x45, 0x95, 0xeb, 0x60, 0xea, 0x47, 0x1d, 0x3b,
	0xab, 0xa4, 0x12, 0x6b, 0x25, 0x1a, 0xbd, 0xfc, 0xeb, 0x80, 0xab, 0x02, 0x25, 0x31, 0x38, 0x31,
	0xee, 0xc8, 0xc3, 0xf0, 0xce, 0x1b, 0x15, 0x1e, 0x6e, 0x53, 0x40, 0xff, 0x47, 0x69, 0xb4, 0xd1,
	0x33, 0xf2, 0x19, 0xbc, 0xa6, 0x01, 0xf2, 0xa8, 0x87, 0xdf, 0x29, 0x3a, 0x78, 0x3c, 0xc0, 0x6a,
	0x07, 0x6f, 0x61, 0xd2, 0x69, 0x98, 0x3c, 0xeb, 0x79, 0xf3, 0xae, 0x7d, 0x0a, 0x9e, 0x9f, 0x46,
	0x3e, 0xb6, 0xd1, 0xb4, 0xd9, 0x6b, 0xa3, 0xb3, 0x3b, 0xbd, 0x36, 0xba, 0x2b, 0x41, 0xcf, 0xc8,
	0x17, 0x18, 0xeb, 0x42, 0x49, 0xdf, 0x3b, 0xdd, 0xd5, 0x08, 0x9e, 0x0c, 0xd1, 0xcc, 0xec, 0xaf,
	0x9e, 0xfa, 0x39, 0xbe, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xd7, 0xf1, 0x1b, 0x2b, 0x05,
	0x00, 0x00,
}
