// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_mnhosted_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SignUpRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SignUpResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *SignUpResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SignUpResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SignInRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SignInRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SignInResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *SignInResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "go.mnhosted.srv.user.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "go.mnhosted.srv.user.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "go.mnhosted.srv.user.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "go.mnhosted.srv.user.SignInResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x37, 0xad, 0x56, 0x1c, 0x70, 0x91, 0x20, 0x12, 0x3c, 0x2d, 0xd1, 0xc3, 0x9e, 0x72,
	0xd0, 0xab, 0x17, 0x8f, 0x0b, 0x9e, 0x22, 0x7d, 0x80, 0xda, 0x0c, 0xb5, 0x87, 0x26, 0x31, 0x93,
	0xea, 0x8b, 0xf9, 0x80, 0x92, 0xb6, 0x51, 0x04, 0x29, 0xe8, 0x2d, 0x3f, 0x13, 0x3e, 0xbe, 0x7f,
	0x06, 0x60, 0x24, 0x0c, 0xca, 0x07, 0x17, 0x1d, 0xbf, 0xe8, 0x9c, 0x1a, 0xec, 0x8b, 0xa3, 0x88,
	0x46, 0x51, 0x78, 0x53, 0x69, 0x26, 0x1f, 0xe0, 0xec, 0xa9, 0xef, 0x6c, 0xed, 0x35, 0xbe, 0x8e,
	0x48, 0x91, 0x0b, 0x38, 0x69, 0xda, 0xd6, 0x8d, 0x36, 0x0a, 0xb6, 0x63, 0xfb, 0x53, 0x9d, 0x23,
	0xbf, 0x84, 0xca, 0x37, 0x44, 0xef, 0x46, 0x14, 0xd3, 0x60, 0x49, 0xf2, 0x11, 0xb6, 0x19, 0x41,
	0xde, 0x59, 0xc2, 0xc4, 0x08, 0x48, 0xad, 0x33, 0x38, 0x31, 0x8e, 0x75, 0x8e, 0xfc, 0x1c, 0xca,
	0x81, 0xba, 0x05, 0x90, 0x9e, 0x7c, 0x0b, 0x45, 0x6f, 0x44, 0xb9, 0x63, 0xfb, 0x52, 0x17, 0xbd,
	0xc9, 0x42, 0x07, 0xfb, 0x7f, 0xa1, 0xfb, 0x59, 0x28, 0x21, 0xfe, 0x2e, 0x74, 0xfb, 0xc1, 0xe0,
	0xa8, 0x26, 0x0c, 0xbc, 0x86, 0x6a, 0xee, 0xc5, 0xaf, 0xd5, 0x6f, 0xbb, 0x53, 0x3f, 0x16, 0x77,
	0x75, 0xb3, 0xfe, 0x69, 0x36, 0x91, 0x9b, 0x8c, 0x3d, 0xd8, 0x35, 0xec, 0x57, 0xfd, 0x35, 0xec,
	0x77, 0x41, 0xb9, 0x79, 0xae, 0xa6, 0x2b, 0xdf, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x2d,
	0xbb, 0x78, 0xf3, 0x01, 0x00, 0x00,
}
