// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_mnhosted_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SignUpRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SignUpResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *SignUpResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SignUpResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SignInRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SignInRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SignInResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *SignInResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SignInResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SignInResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SignOutRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRequest) Reset()         { *m = SignOutRequest{} }
func (m *SignOutRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutRequest) ProtoMessage()    {}
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRequest.Unmarshal(m, b)
}
func (m *SignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRequest.Marshal(b, m, deterministic)
}
func (m *SignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRequest.Merge(m, src)
}
func (m *SignOutRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutRequest.Size(m)
}
func (m *SignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRequest proto.InternalMessageInfo

func (m *SignOutRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type SignOutResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutResponse) Reset()         { *m = SignOutResponse{} }
func (m *SignOutResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutResponse) ProtoMessage()    {}
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *SignOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResponse.Unmarshal(m, b)
}
func (m *SignOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResponse.Marshal(b, m, deterministic)
}
func (m *SignOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResponse.Merge(m, src)
}
func (m *SignOutResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutResponse.Size(m)
}
func (m *SignOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResponse proto.InternalMessageInfo

func (m *SignOutResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *SignOutResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetInfoRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetInfoResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	WalletAddress        string   `protobuf:"bytes,3,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	MNCount              int32    `protobuf:"varint,5,opt,name=MNCount,proto3" json:"MNCount,omitempty"`
	Msg                  string   `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *GetInfoResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetInfoResponse) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *GetInfoResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetInfoResponse) GetMNCount() int32 {
	if m != nil {
		return m.MNCount
	}
	return 0
}

func (m *GetInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type MailCodeRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailCodeRequest) Reset()         { *m = MailCodeRequest{} }
func (m *MailCodeRequest) String() string { return proto.CompactTextString(m) }
func (*MailCodeRequest) ProtoMessage()    {}
func (*MailCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *MailCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailCodeRequest.Unmarshal(m, b)
}
func (m *MailCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailCodeRequest.Marshal(b, m, deterministic)
}
func (m *MailCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailCodeRequest.Merge(m, src)
}
func (m *MailCodeRequest) XXX_Size() int {
	return xxx_messageInfo_MailCodeRequest.Size(m)
}
func (m *MailCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailCodeRequest proto.InternalMessageInfo

func (m *MailCodeRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type MailCodeResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailCodeResponse) Reset()         { *m = MailCodeResponse{} }
func (m *MailCodeResponse) String() string { return proto.CompactTextString(m) }
func (*MailCodeResponse) ProtoMessage()    {}
func (*MailCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *MailCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailCodeResponse.Unmarshal(m, b)
}
func (m *MailCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailCodeResponse.Marshal(b, m, deterministic)
}
func (m *MailCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailCodeResponse.Merge(m, src)
}
func (m *MailCodeResponse) XXX_Size() int {
	return xxx_messageInfo_MailCodeResponse.Size(m)
}
func (m *MailCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailCodeResponse proto.InternalMessageInfo

func (m *MailCodeResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

type ResetRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Authcode             string   `protobuf:"bytes,3,opt,name=authcode,proto3" json:"authcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

func (m *ResetRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ResetRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *ResetRequest) GetAuthcode() string {
	if m != nil {
		return m.Authcode
	}
	return ""
}

type ResetResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *ResetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "go.mnhosted.srv.user.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "go.mnhosted.srv.user.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "go.mnhosted.srv.user.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "go.mnhosted.srv.user.SignInResponse")
	proto.RegisterType((*SignOutRequest)(nil), "go.mnhosted.srv.user.SignOutRequest")
	proto.RegisterType((*SignOutResponse)(nil), "go.mnhosted.srv.user.SignOutResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "go.mnhosted.srv.user.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "go.mnhosted.srv.user.GetInfoResponse")
	proto.RegisterType((*MailCodeRequest)(nil), "go.mnhosted.srv.user.MailCodeRequest")
	proto.RegisterType((*MailCodeResponse)(nil), "go.mnhosted.srv.user.MailCodeResponse")
	proto.RegisterType((*ResetRequest)(nil), "go.mnhosted.srv.user.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "go.mnhosted.srv.user.ResetResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6b, 0xdb, 0x30,
	0x10, 0xc7, 0xe3, 0xfc, 0x70, 0xdb, 0x63, 0x69, 0x8a, 0x28, 0xc5, 0xf8, 0xa9, 0xa8, 0xdd, 0x08,
	0x6c, 0xf8, 0x61, 0x7b, 0x1c, 0x7b, 0x28, 0x1d, 0x8c, 0xc0, 0xba, 0x81, 0x46, 0x60, 0xb0, 0xbd,
	0x38, 0xd1, 0x2d, 0x35, 0x73, 0x25, 0xcf, 0x92, 0xd7, 0xbf, 0x65, 0x7f, 0xc6, 0xfe, 0xc3, 0x21,
	0xd9, 0xb2, 0xe3, 0xd2, 0xd8, 0x34, 0x7b, 0xcb, 0x45, 0xdf, 0xfb, 0xdc, 0xe9, 0xf4, 0x3d, 0x03,
	0x14, 0x0a, 0xf3, 0x28, 0xcb, 0xa5, 0x96, 0xe4, 0x74, 0x23, 0xa3, 0x3b, 0x71, 0x2b, 0x95, 0x46,
	0x1e, 0xa9, 0xfc, 0x77, 0x64, 0xce, 0xe8, 0x15, 0x4c, 0xbf, 0x24, 0x1b, 0xb1, 0xcc, 0x18, 0xfe,
	0x2a, 0x50, 0x69, 0x12, 0xc0, 0x41, 0xbc, 0x5e, 0xcb, 0x42, 0xe8, 0xc0, 0x3b, 0xf7, 0xe6, 0x47,
	0xcc, 0x85, 0xe4, 0x0c, 0xfc, 0x2c, 0x56, 0xea, 0x9e, 0x07, 0x43, 0x7b, 0x50, 0x45, 0xf4, 0x23,
	0x1c, 0x3b, 0x84, 0xca, 0xa4, 0x50, 0x68, 0x18, 0x39, 0xaa, 0xb5, 0xe4, 0x68, 0x19, 0x13, 0xe6,
	0x42, 0x72, 0x02, 0xa3, 0x3b, 0xb5, 0xa9, 0x00, 0xe6, 0x27, 0x39, 0x86, 0x61, 0xc2, 0x83, 0xd1,
	0xb9, 0x37, 0x1f, 0xb1, 0x61, 0xc2, 0x5d, 0x43, 0x0b, 0xb1, 0x7f, 0x43, 0xab, 0xb2, 0x21, 0x83,
	0xf8, 0xff, 0x86, 0xc8, 0x29, 0x4c, 0xb4, 0xfc, 0x89, 0x22, 0x18, 0x5b, 0x4d, 0x19, 0xd0, 0x79,
	0x59, 0xe3, 0x73, 0xa1, 0x5d, 0x9f, 0x67, 0xe0, 0x9b, 0x89, 0x2e, 0xde, 0xdb, 0x12, 0x23, 0x56,
	0x45, 0xf4, 0x1d, 0xcc, 0x6a, 0xe5, 0xd3, 0xdb, 0x31, 0x85, 0x3e, 0xa0, 0x5e, 0x88, 0x1f, 0xb2,
	0xaf, 0xd0, 0x5f, 0x0f, 0x66, 0xb5, 0xb4, 0xb7, 0xd2, 0xd6, 0x58, 0x87, 0xed, 0xb1, 0x5e, 0xc2,
	0xf4, 0x3e, 0x4e, 0x53, 0xd4, 0x57, 0x9c, 0xe7, 0xa8, 0x94, 0x9d, 0xc5, 0x11, 0x6b, 0xff, 0x69,
	0xf2, 0x57, 0x71, 0x1a, 0x8b, 0x35, 0xda, 0xc1, 0x78, 0xcc, 0x85, 0xe6, 0xe4, 0xe6, 0xd3, 0xb5,
	0x25, 0x4f, 0xca, 0x9a, 0x55, 0xe8, 0x6e, 0xe7, 0x37, 0xb7, 0x7b, 0x09, 0xb3, 0x9b, 0x38, 0x49,
	0xaf, 0x25, 0xc7, 0xde, 0xf7, 0xa6, 0xaf, 0xe0, 0xa4, 0x11, 0xf7, 0x5d, 0x90, 0x7e, 0x87, 0x67,
	0x0c, 0x15, 0xea, 0xbd, 0x7d, 0x44, 0x42, 0x38, 0x8c, 0x0b, 0x7d, 0x6b, 0xe1, 0xe5, 0x0c, 0xea,
	0x98, 0xbe, 0x85, 0x69, 0x45, 0x7f, 0xfa, 0x9b, 0xbe, 0xfe, 0x33, 0x86, 0xf1, 0x52, 0x61, 0x4e,
	0x96, 0xe0, 0x97, 0xab, 0x43, 0x2e, 0xa2, 0xc7, 0xd6, 0x33, 0x6a, 0xed, 0x66, 0x78, 0xd9, 0x2d,
	0x2a, 0x3b, 0xa1, 0x03, 0x87, 0x5d, 0x88, 0x2e, 0x6c, 0xbd, 0x61, 0x5d, 0xd8, 0x66, 0x87, 0xe8,
	0x80, 0x7c, 0x85, 0x83, 0xca, 0xc9, 0xa4, 0x23, 0xa5, 0x59, 0x89, 0xf0, 0x79, 0x8f, 0x6a, 0x9b,
	0x5c, 0x39, 0x77, 0x17, 0xb9, 0xbd, 0x03, 0xbb, 0xc8, 0x0f, 0xec, 0x4f, 0x07, 0xe4, 0x1b, 0x1c,
	0x3a, 0xcf, 0x90, 0x1d, 0x49, 0x0f, 0x0c, 0x18, 0xbe, 0xe8, 0x93, 0xd5, 0x70, 0x06, 0x13, 0x6b,
	0x02, 0x42, 0x1f, 0x4f, 0xd9, 0xf6, 0x5f, 0x78, 0xd1, 0xa9, 0x71, 0xcc, 0x95, 0x6f, 0xbf, 0xd6,
	0x6f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xa2, 0xf2, 0x61, 0xbb, 0x05, 0x00, 0x00,
}
