// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package go_mnhosted_srv_node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoinListRequest struct {
	CurPage              int32    `protobuf:"varint,1,opt,name=curPage,proto3" json:"curPage,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinListRequest) Reset()         { *m = CoinListRequest{} }
func (m *CoinListRequest) String() string { return proto.CompactTextString(m) }
func (*CoinListRequest) ProtoMessage()    {}
func (*CoinListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *CoinListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinListRequest.Unmarshal(m, b)
}
func (m *CoinListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinListRequest.Marshal(b, m, deterministic)
}
func (m *CoinListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinListRequest.Merge(m, src)
}
func (m *CoinListRequest) XXX_Size() int {
	return xxx_messageInfo_CoinListRequest.Size(m)
}
func (m *CoinListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinListRequest proto.InternalMessageInfo

func (m *CoinListRequest) GetCurPage() int32 {
	if m != nil {
		return m.CurPage
	}
	return 0
}

func (m *CoinListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type CoinItem struct {
	MNRequired           int32    `protobuf:"varint,1,opt,name=MNRequired,proto3" json:"MNRequired,omitempty"`
	CoinName             string   `protobuf:"bytes,2,opt,name=coinName,proto3" json:"coinName,omitempty"`
	DPrice               float64  `protobuf:"fixed64,3,opt,name=DPrice,proto3" json:"DPrice,omitempty"`
	MPrice               float64  `protobuf:"fixed64,4,opt,name=MPrice,proto3" json:"MPrice,omitempty"`
	YPrice               float64  `protobuf:"fixed64,5,opt,name=YPrice,proto3" json:"YPrice,omitempty"`
	Volume               int32    `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Roi                  int32    `protobuf:"varint,7,opt,name=roi,proto3" json:"roi,omitempty"`
	MonthlyIncome        int32    `protobuf:"varint,8,opt,name=monthlyIncome,proto3" json:"monthlyIncome,omitempty"`
	MNHosted             int32    `protobuf:"varint,9,opt,name=MNHosted,proto3" json:"MNHosted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinItem) Reset()         { *m = CoinItem{} }
func (m *CoinItem) String() string { return proto.CompactTextString(m) }
func (*CoinItem) ProtoMessage()    {}
func (*CoinItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *CoinItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinItem.Unmarshal(m, b)
}
func (m *CoinItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinItem.Marshal(b, m, deterministic)
}
func (m *CoinItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinItem.Merge(m, src)
}
func (m *CoinItem) XXX_Size() int {
	return xxx_messageInfo_CoinItem.Size(m)
}
func (m *CoinItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinItem.DiscardUnknown(m)
}

var xxx_messageInfo_CoinItem proto.InternalMessageInfo

func (m *CoinItem) GetMNRequired() int32 {
	if m != nil {
		return m.MNRequired
	}
	return 0
}

func (m *CoinItem) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *CoinItem) GetDPrice() float64 {
	if m != nil {
		return m.DPrice
	}
	return 0
}

func (m *CoinItem) GetMPrice() float64 {
	if m != nil {
		return m.MPrice
	}
	return 0
}

func (m *CoinItem) GetYPrice() float64 {
	if m != nil {
		return m.YPrice
	}
	return 0
}

func (m *CoinItem) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *CoinItem) GetRoi() int32 {
	if m != nil {
		return m.Roi
	}
	return 0
}

func (m *CoinItem) GetMonthlyIncome() int32 {
	if m != nil {
		return m.MonthlyIncome
	}
	return 0
}

func (m *CoinItem) GetMNHosted() int32 {
	if m != nil {
		return m.MNHosted
	}
	return 0
}

type CoinListResponse struct {
	Rescode              int32       `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Coinlist             []*CoinItem `protobuf:"bytes,2,rep,name=coinlist,proto3" json:"coinlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CoinListResponse) Reset()         { *m = CoinListResponse{} }
func (m *CoinListResponse) String() string { return proto.CompactTextString(m) }
func (*CoinListResponse) ProtoMessage()    {}
func (*CoinListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *CoinListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinListResponse.Unmarshal(m, b)
}
func (m *CoinListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinListResponse.Marshal(b, m, deterministic)
}
func (m *CoinListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinListResponse.Merge(m, src)
}
func (m *CoinListResponse) XXX_Size() int {
	return xxx_messageInfo_CoinListResponse.Size(m)
}
func (m *CoinListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoinListResponse proto.InternalMessageInfo

func (m *CoinListResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *CoinListResponse) GetCoinlist() []*CoinItem {
	if m != nil {
		return m.Coinlist
	}
	return nil
}

type CoinItemRequest struct {
	CoinName             string   `protobuf:"bytes,1,opt,name=coinName,proto3" json:"coinName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinItemRequest) Reset()         { *m = CoinItemRequest{} }
func (m *CoinItemRequest) String() string { return proto.CompactTextString(m) }
func (*CoinItemRequest) ProtoMessage()    {}
func (*CoinItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *CoinItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinItemRequest.Unmarshal(m, b)
}
func (m *CoinItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinItemRequest.Marshal(b, m, deterministic)
}
func (m *CoinItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinItemRequest.Merge(m, src)
}
func (m *CoinItemRequest) XXX_Size() int {
	return xxx_messageInfo_CoinItemRequest.Size(m)
}
func (m *CoinItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinItemRequest proto.InternalMessageInfo

func (m *CoinItemRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

type CoinItemResponse struct {
	Rescode              int32     `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Coin                 *CoinItem `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CoinItemResponse) Reset()         { *m = CoinItemResponse{} }
func (m *CoinItemResponse) String() string { return proto.CompactTextString(m) }
func (*CoinItemResponse) ProtoMessage()    {}
func (*CoinItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}

func (m *CoinItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinItemResponse.Unmarshal(m, b)
}
func (m *CoinItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinItemResponse.Marshal(b, m, deterministic)
}
func (m *CoinItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinItemResponse.Merge(m, src)
}
func (m *CoinItemResponse) XXX_Size() int {
	return xxx_messageInfo_CoinItemResponse.Size(m)
}
func (m *CoinItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoinItemResponse proto.InternalMessageInfo

func (m *CoinItemResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *CoinItemResponse) GetCoin() *CoinItem {
	if m != nil {
		return m.Coin
	}
	return nil
}

type GetCountRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountRequest) Reset()         { *m = GetCountRequest{} }
func (m *GetCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountRequest) ProtoMessage()    {}
func (*GetCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{5}
}

func (m *GetCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountRequest.Unmarshal(m, b)
}
func (m *GetCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountRequest.Marshal(b, m, deterministic)
}
func (m *GetCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountRequest.Merge(m, src)
}
func (m *GetCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountRequest.Size(m)
}
func (m *GetCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountRequest proto.InternalMessageInfo

func (m *GetCountRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetCountResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountResponse) Reset()         { *m = GetCountResponse{} }
func (m *GetCountResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountResponse) ProtoMessage()    {}
func (*GetCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{6}
}

func (m *GetCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountResponse.Unmarshal(m, b)
}
func (m *GetCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountResponse.Marshal(b, m, deterministic)
}
func (m *GetCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountResponse.Merge(m, src)
}
func (m *GetCountResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountResponse.Size(m)
}
func (m *GetCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountResponse proto.InternalMessageInfo

func (m *GetCountResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MasterNodeListRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeListRequest) Reset()         { *m = MasterNodeListRequest{} }
func (m *MasterNodeListRequest) String() string { return proto.CompactTextString(m) }
func (*MasterNodeListRequest) ProtoMessage()    {}
func (*MasterNodeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{7}
}

func (m *MasterNodeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeListRequest.Unmarshal(m, b)
}
func (m *MasterNodeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeListRequest.Marshal(b, m, deterministic)
}
func (m *MasterNodeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeListRequest.Merge(m, src)
}
func (m *MasterNodeListRequest) XXX_Size() int {
	return xxx_messageInfo_MasterNodeListRequest.Size(m)
}
func (m *MasterNodeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeListRequest proto.InternalMessageInfo

func (m *MasterNodeListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type MasternodeItem struct {
	MNID                 int64    `protobuf:"varint,1,opt,name=MNID,proto3" json:"MNID,omitempty"`
	CoinName             string   `protobuf:"bytes,2,opt,name=coinName,proto3" json:"coinName,omitempty"`
	MNKey                string   `protobuf:"bytes,3,opt,name=MNKey,proto3" json:"MNKey,omitempty"`
	SyncStatus           int32    `protobuf:"varint,4,opt,name=SyncStatus,proto3" json:"SyncStatus,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	ExpireTime           string   `protobuf:"bytes,6,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasternodeItem) Reset()         { *m = MasternodeItem{} }
func (m *MasternodeItem) String() string { return proto.CompactTextString(m) }
func (*MasternodeItem) ProtoMessage()    {}
func (*MasternodeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{8}
}

func (m *MasternodeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasternodeItem.Unmarshal(m, b)
}
func (m *MasternodeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasternodeItem.Marshal(b, m, deterministic)
}
func (m *MasternodeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasternodeItem.Merge(m, src)
}
func (m *MasternodeItem) XXX_Size() int {
	return xxx_messageInfo_MasternodeItem.Size(m)
}
func (m *MasternodeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MasternodeItem.DiscardUnknown(m)
}

var xxx_messageInfo_MasternodeItem proto.InternalMessageInfo

func (m *MasternodeItem) GetMNID() int64 {
	if m != nil {
		return m.MNID
	}
	return 0
}

func (m *MasternodeItem) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *MasternodeItem) GetMNKey() string {
	if m != nil {
		return m.MNKey
	}
	return ""
}

func (m *MasternodeItem) GetSyncStatus() int32 {
	if m != nil {
		return m.SyncStatus
	}
	return 0
}

func (m *MasternodeItem) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MasternodeItem) GetExpireTime() string {
	if m != nil {
		return m.ExpireTime
	}
	return ""
}

type MasterNodeListResponse struct {
	Rescode              int32             `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	Masternodelist       []*MasternodeItem `protobuf:"bytes,2,rep,name=masternodelist,proto3" json:"masternodelist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MasterNodeListResponse) Reset()         { *m = MasterNodeListResponse{} }
func (m *MasterNodeListResponse) String() string { return proto.CompactTextString(m) }
func (*MasterNodeListResponse) ProtoMessage()    {}
func (*MasterNodeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{9}
}

func (m *MasterNodeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeListResponse.Unmarshal(m, b)
}
func (m *MasterNodeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeListResponse.Marshal(b, m, deterministic)
}
func (m *MasterNodeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeListResponse.Merge(m, src)
}
func (m *MasterNodeListResponse) XXX_Size() int {
	return xxx_messageInfo_MasterNodeListResponse.Size(m)
}
func (m *MasterNodeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeListResponse proto.InternalMessageInfo

func (m *MasterNodeListResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *MasterNodeListResponse) GetMasternodelist() []*MasternodeItem {
	if m != nil {
		return m.Masternodelist
	}
	return nil
}

type MasterNodeNewRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CoinName             string   `protobuf:"bytes,2,opt,name=coinName,proto3" json:"coinName,omitempty"`
	MNKey                string   `protobuf:"bytes,3,opt,name=MNKey,proto3" json:"MNKey,omitempty"`
	ExternalIp           string   `protobuf:"bytes,4,opt,name=externalIp,proto3" json:"externalIp,omitempty"`
	TimeType             string   `protobuf:"bytes,5,opt,name=timeType,proto3" json:"timeType,omitempty"`
	OrderID              int64    `protobuf:"varint,6,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeNewRequest) Reset()         { *m = MasterNodeNewRequest{} }
func (m *MasterNodeNewRequest) String() string { return proto.CompactTextString(m) }
func (*MasterNodeNewRequest) ProtoMessage()    {}
func (*MasterNodeNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{10}
}

func (m *MasterNodeNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeNewRequest.Unmarshal(m, b)
}
func (m *MasterNodeNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeNewRequest.Marshal(b, m, deterministic)
}
func (m *MasterNodeNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeNewRequest.Merge(m, src)
}
func (m *MasterNodeNewRequest) XXX_Size() int {
	return xxx_messageInfo_MasterNodeNewRequest.Size(m)
}
func (m *MasterNodeNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeNewRequest proto.InternalMessageInfo

func (m *MasterNodeNewRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MasterNodeNewRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *MasterNodeNewRequest) GetMNKey() string {
	if m != nil {
		return m.MNKey
	}
	return ""
}

func (m *MasterNodeNewRequest) GetExternalIp() string {
	if m != nil {
		return m.ExternalIp
	}
	return ""
}

func (m *MasterNodeNewRequest) GetTimeType() string {
	if m != nil {
		return m.TimeType
	}
	return ""
}

func (m *MasterNodeNewRequest) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type MasterNodeNewResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeNewResponse) Reset()         { *m = MasterNodeNewResponse{} }
func (m *MasterNodeNewResponse) String() string { return proto.CompactTextString(m) }
func (*MasterNodeNewResponse) ProtoMessage()    {}
func (*MasterNodeNewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{11}
}

func (m *MasterNodeNewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeNewResponse.Unmarshal(m, b)
}
func (m *MasterNodeNewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeNewResponse.Marshal(b, m, deterministic)
}
func (m *MasterNodeNewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeNewResponse.Merge(m, src)
}
func (m *MasterNodeNewResponse) XXX_Size() int {
	return xxx_messageInfo_MasterNodeNewResponse.Size(m)
}
func (m *MasterNodeNewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeNewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeNewResponse proto.InternalMessageInfo

func (m *MasterNodeNewResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

type MasterNodeRenewRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CoinName             string   `protobuf:"bytes,2,opt,name=coinName,proto3" json:"coinName,omitempty"`
	MNKey                string   `protobuf:"bytes,3,opt,name=MNKey,proto3" json:"MNKey,omitempty"`
	ExternalIp           string   `protobuf:"bytes,4,opt,name=externalIp,proto3" json:"externalIp,omitempty"`
	TimeType             string   `protobuf:"bytes,5,opt,name=timeType,proto3" json:"timeType,omitempty"`
	TimeNum              int32    `protobuf:"varint,6,opt,name=timeNum,proto3" json:"timeNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeRenewRequest) Reset()         { *m = MasterNodeRenewRequest{} }
func (m *MasterNodeRenewRequest) String() string { return proto.CompactTextString(m) }
func (*MasterNodeRenewRequest) ProtoMessage()    {}
func (*MasterNodeRenewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{12}
}

func (m *MasterNodeRenewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeRenewRequest.Unmarshal(m, b)
}
func (m *MasterNodeRenewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeRenewRequest.Marshal(b, m, deterministic)
}
func (m *MasterNodeRenewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeRenewRequest.Merge(m, src)
}
func (m *MasterNodeRenewRequest) XXX_Size() int {
	return xxx_messageInfo_MasterNodeRenewRequest.Size(m)
}
func (m *MasterNodeRenewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeRenewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeRenewRequest proto.InternalMessageInfo

func (m *MasterNodeRenewRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MasterNodeRenewRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *MasterNodeRenewRequest) GetMNKey() string {
	if m != nil {
		return m.MNKey
	}
	return ""
}

func (m *MasterNodeRenewRequest) GetExternalIp() string {
	if m != nil {
		return m.ExternalIp
	}
	return ""
}

func (m *MasterNodeRenewRequest) GetTimeType() string {
	if m != nil {
		return m.TimeType
	}
	return ""
}

func (m *MasterNodeRenewRequest) GetTimeNum() int32 {
	if m != nil {
		return m.TimeNum
	}
	return 0
}

type MasterNodeRenewResponse struct {
	Rescode              int32    `protobuf:"varint,1,opt,name=rescode,proto3" json:"rescode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeRenewResponse) Reset()         { *m = MasterNodeRenewResponse{} }
func (m *MasterNodeRenewResponse) String() string { return proto.CompactTextString(m) }
func (*MasterNodeRenewResponse) ProtoMessage()    {}
func (*MasterNodeRenewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{13}
}

func (m *MasterNodeRenewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeRenewResponse.Unmarshal(m, b)
}
func (m *MasterNodeRenewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeRenewResponse.Marshal(b, m, deterministic)
}
func (m *MasterNodeRenewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeRenewResponse.Merge(m, src)
}
func (m *MasterNodeRenewResponse) XXX_Size() int {
	return xxx_messageInfo_MasterNodeRenewResponse.Size(m)
}
func (m *MasterNodeRenewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeRenewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeRenewResponse proto.InternalMessageInfo

func (m *MasterNodeRenewResponse) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

type MasterNodeCheckRequest struct {
	CoinName             string   `protobuf:"bytes,1,opt,name=coinName,proto3" json:"coinName,omitempty"`
	MNKey                string   `protobuf:"bytes,2,opt,name=MNKey,proto3" json:"MNKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeCheckRequest) Reset()         { *m = MasterNodeCheckRequest{} }
func (m *MasterNodeCheckRequest) String() string { return proto.CompactTextString(m) }
func (*MasterNodeCheckRequest) ProtoMessage()    {}
func (*MasterNodeCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{14}
}

func (m *MasterNodeCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeCheckRequest.Unmarshal(m, b)
}
func (m *MasterNodeCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeCheckRequest.Marshal(b, m, deterministic)
}
func (m *MasterNodeCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeCheckRequest.Merge(m, src)
}
func (m *MasterNodeCheckRequest) XXX_Size() int {
	return xxx_messageInfo_MasterNodeCheckRequest.Size(m)
}
func (m *MasterNodeCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeCheckRequest proto.InternalMessageInfo

func (m *MasterNodeCheckRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *MasterNodeCheckRequest) GetMNKey() string {
	if m != nil {
		return m.MNKey
	}
	return ""
}

type MasterNodeCheckResponse struct {
	IsExsit              bool     `protobuf:"varint,1,opt,name=IsExsit,proto3" json:"IsExsit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterNodeCheckResponse) Reset()         { *m = MasterNodeCheckResponse{} }
func (m *MasterNodeCheckResponse) String() string { return proto.CompactTextString(m) }
func (*MasterNodeCheckResponse) ProtoMessage()    {}
func (*MasterNodeCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{15}
}

func (m *MasterNodeCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterNodeCheckResponse.Unmarshal(m, b)
}
func (m *MasterNodeCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterNodeCheckResponse.Marshal(b, m, deterministic)
}
func (m *MasterNodeCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterNodeCheckResponse.Merge(m, src)
}
func (m *MasterNodeCheckResponse) XXX_Size() int {
	return xxx_messageInfo_MasterNodeCheckResponse.Size(m)
}
func (m *MasterNodeCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterNodeCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterNodeCheckResponse proto.InternalMessageInfo

func (m *MasterNodeCheckResponse) GetIsExsit() bool {
	if m != nil {
		return m.IsExsit
	}
	return false
}

func init() {
	proto.RegisterType((*CoinListRequest)(nil), "go.mnhosted.srv.node.CoinListRequest")
	proto.RegisterType((*CoinItem)(nil), "go.mnhosted.srv.node.CoinItem")
	proto.RegisterType((*CoinListResponse)(nil), "go.mnhosted.srv.node.CoinListResponse")
	proto.RegisterType((*CoinItemRequest)(nil), "go.mnhosted.srv.node.CoinItemRequest")
	proto.RegisterType((*CoinItemResponse)(nil), "go.mnhosted.srv.node.CoinItemResponse")
	proto.RegisterType((*GetCountRequest)(nil), "go.mnhosted.srv.node.GetCountRequest")
	proto.RegisterType((*GetCountResponse)(nil), "go.mnhosted.srv.node.GetCountResponse")
	proto.RegisterType((*MasterNodeListRequest)(nil), "go.mnhosted.srv.node.MasterNodeListRequest")
	proto.RegisterType((*MasternodeItem)(nil), "go.mnhosted.srv.node.MasternodeItem")
	proto.RegisterType((*MasterNodeListResponse)(nil), "go.mnhosted.srv.node.MasterNodeListResponse")
	proto.RegisterType((*MasterNodeNewRequest)(nil), "go.mnhosted.srv.node.MasterNodeNewRequest")
	proto.RegisterType((*MasterNodeNewResponse)(nil), "go.mnhosted.srv.node.MasterNodeNewResponse")
	proto.RegisterType((*MasterNodeRenewRequest)(nil), "go.mnhosted.srv.node.MasterNodeRenewRequest")
	proto.RegisterType((*MasterNodeRenewResponse)(nil), "go.mnhosted.srv.node.MasterNodeRenewResponse")
	proto.RegisterType((*MasterNodeCheckRequest)(nil), "go.mnhosted.srv.node.MasterNodeCheckRequest")
	proto.RegisterType((*MasterNodeCheckResponse)(nil), "go.mnhosted.srv.node.MasterNodeCheckResponse")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 742 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0x8d, 0xc9, 0x1f, 0x92, 0x41, 0x3f, 0x40, 0xab, 0xfc, 0xa8, 0x95, 0x03, 0x42, 0x2b, 0xa8,
	0xd2, 0x16, 0x52, 0x35, 0xdc, 0x7a, 0x85, 0x8a, 0xa6, 0x25, 0x16, 0x32, 0xa8, 0x12, 0xaa, 0x54,
	0x11, 0xec, 0x29, 0xb1, 0x1a, 0x7b, 0x53, 0x7b, 0x03, 0xa4, 0xa7, 0xf6, 0x4b, 0x55, 0x3d, 0xf5,
	0x83, 0xf5, 0x54, 0xed, 0xae, 0xbd, 0x59, 0xa7, 0x80, 0xa3, 0x9e, 0x7a, 0xf3, 0xbc, 0x9d, 0x9d,
	0x9d, 0x79, 0xf3, 0x76, 0xd6, 0x00, 0x11, 0xf3, 0xb1, 0x33, 0x8e, 0x19, 0x67, 0xa4, 0x79, 0xc5,
	0x3a, 0x61, 0x34, 0x64, 0x09, 0x47, 0xbf, 0x93, 0xc4, 0xd7, 0x1d, 0xb1, 0x46, 0x8f, 0x60, 0xed,
	0x80, 0x05, 0xd1, 0x71, 0x90, 0x70, 0x17, 0x3f, 0x4f, 0x30, 0xe1, 0xc4, 0x86, 0x65, 0x6f, 0x12,
	0x9f, 0x0c, 0xae, 0xd0, 0xb6, 0xb6, 0xac, 0x76, 0xd5, 0xcd, 0x4c, 0xd2, 0x82, 0xfa, 0x78, 0x70,
	0x85, 0xa7, 0xc1, 0x17, 0xb4, 0x97, 0xe4, 0x92, 0xb6, 0xe9, 0x2f, 0x0b, 0xea, 0x22, 0x52, 0x8f,
	0x63, 0x48, 0x36, 0x01, 0xfa, 0x8e, 0x88, 0x17, 0xc4, 0xe8, 0xa7, 0x51, 0x0c, 0x44, 0x04, 0xf2,
	0x58, 0x10, 0x39, 0x83, 0x50, 0x05, 0x6a, 0xb8, 0xda, 0x26, 0x1b, 0x50, 0x3b, 0x3c, 0x89, 0x03,
	0x0f, 0xed, 0xf2, 0x96, 0xd5, 0xb6, 0xdc, 0xd4, 0x12, 0x78, 0x5f, 0xe1, 0x15, 0x85, 0xf7, 0x35,
	0x7e, 0xae, 0xf0, 0xaa, 0xc2, 0xcf, 0x35, 0x7e, 0xcd, 0x46, 0x93, 0x10, 0xed, 0x9a, 0x3c, 0x3f,
	0xb5, 0xc8, 0x3a, 0x94, 0x63, 0x16, 0xd8, 0xcb, 0x12, 0x14, 0x9f, 0x64, 0x1b, 0xfe, 0x0b, 0x59,
	0xc4, 0x87, 0xa3, 0x69, 0x2f, 0xf2, 0x58, 0x88, 0x76, 0x5d, 0xae, 0xe5, 0x41, 0x91, 0x73, 0xdf,
	0x79, 0x2d, 0xe9, 0xb3, 0x1b, 0xaa, 0xf8, 0xcc, 0xa6, 0x43, 0x58, 0x9f, 0xb1, 0x98, 0x8c, 0x59,
	0x94, 0xa0, 0xa0, 0x31, 0xc6, 0xc4, 0x63, 0xbe, 0xa6, 0x31, 0x35, 0xc9, 0x4b, 0x55, 0xfd, 0x28,
	0x48, 0xb8, 0xbd, 0xb4, 0x55, 0x6e, 0xaf, 0x74, 0x37, 0x3b, 0x77, 0x35, 0xa7, 0x93, 0xf1, 0xe9,
	0x6a, 0x7f, 0xba, 0xa7, 0xfa, 0x25, 0xd1, 0xb4, 0x5f, 0x26, 0x99, 0x56, 0x9e, 0x4c, 0x7a, 0xa1,
	0x12, 0x53, 0xee, 0x85, 0x89, 0x75, 0xa1, 0x22, 0x76, 0xca, 0x96, 0x14, 0x27, 0x25, 0x7d, 0xe9,
	0x13, 0x58, 0x3b, 0x42, 0x7e, 0xc0, 0x26, 0x91, 0x16, 0xd0, 0x06, 0xd4, 0x26, 0x09, 0xc6, 0xbd,
	0x43, 0x19, 0xbf, 0xec, 0xa6, 0x16, 0x6d, 0xc3, 0xfa, 0xcc, 0x35, 0x4d, 0xa6, 0x09, 0x55, 0x4f,
	0x00, 0x69, 0x2a, 0xca, 0xa0, 0xcf, 0xe1, 0xff, 0xfe, 0x20, 0xe1, 0x18, 0x3b, 0xcc, 0x47, 0x53,
	0x9b, 0x59, 0x68, 0x3f, 0x17, 0xda, 0xa7, 0xdf, 0x2d, 0x58, 0x55, 0x3b, 0x44, 0x8e, 0x52, 0x83,
	0x04, 0x2a, 0x7d, 0x47, 0xe7, 0x20, 0xbf, 0x1f, 0xd4, 0x5d, 0x13, 0xaa, 0x7d, 0xe7, 0x2d, 0x4e,
	0xa5, 0xec, 0x1a, 0xae, 0x32, 0x84, 0x92, 0x4f, 0xa7, 0x91, 0x77, 0xca, 0x07, 0x7c, 0x92, 0x48,
	0xe5, 0x55, 0x5d, 0x03, 0x11, 0xeb, 0x5e, 0x8c, 0x03, 0x8e, 0x67, 0x41, 0xa8, 0x14, 0xd8, 0x70,
	0x0d, 0x44, 0xac, 0xe3, 0xed, 0x38, 0x88, 0xd5, 0x7a, 0x4d, 0xad, 0xcf, 0x10, 0xfa, 0xd5, 0x82,
	0x8d, 0xf9, 0x52, 0x0b, 0xfb, 0x74, 0x0c, 0xab, 0xa1, 0x2e, 0xd6, 0x90, 0xd1, 0xf6, 0xdd, 0x1d,
	0xcb, 0x13, 0xe3, 0xce, 0xed, 0x15, 0xdc, 0x35, 0x67, 0x29, 0x38, 0x78, 0x53, 0x40, 0xf6, 0xdf,
	0xb1, 0x88, 0xb7, 0xe2, 0xcc, 0xc1, 0xa8, 0x37, 0x96, 0x2c, 0x4a, 0x16, 0x32, 0x44, 0x44, 0xe4,
	0x41, 0x88, 0x67, 0xd3, 0x71, 0xc6, 0xa1, 0xb6, 0x05, 0x0d, 0x2c, 0xf6, 0xa5, 0x9c, 0x6a, 0x32,
	0x8d, 0xcc, 0xa4, 0x2f, 0x4c, 0x95, 0xc8, 0xbc, 0x8b, 0x98, 0xa3, 0x3f, 0x72, 0x74, 0xbb, 0x18,
	0xfd, 0x83, 0xd5, 0x8a, 0x6f, 0x67, 0x12, 0xa6, 0x63, 0x2b, 0x33, 0xe9, 0x3e, 0x3c, 0xfa, 0x23,
	0xf3, 0xc2, 0x7a, 0xdf, 0x98, 0xe5, 0x1e, 0x0c, 0xd1, 0xfb, 0xb4, 0xc0, 0xd4, 0x98, 0x95, 0xb5,
	0x64, 0x94, 0x95, 0x4f, 0x20, 0x8d, 0x35, 0x4b, 0xa0, 0x97, 0xbc, 0xba, 0x4d, 0x02, 0x75, 0x8f,
	0xeb, 0x6e, 0x66, 0x76, 0x7f, 0x5a, 0x6a, 0xa6, 0x90, 0x77, 0x50, 0x3e, 0x42, 0x4e, 0x76, 0xee,
	0x1f, 0x2a, 0xc6, 0x3d, 0x6f, 0x3d, 0x2e, 0x72, 0x53, 0x07, 0xd3, 0x12, 0xf9, 0x00, 0x2b, 0x72,
	0xa8, 0xa4, 0x2f, 0xcf, 0x4e, 0xc1, 0xd0, 0x2a, 0x8e, 0x6f, 0xce, 0x4a, 0x5a, 0xea, 0x7e, 0xab,
	0x00, 0xcc, 0x2e, 0x0c, 0xb9, 0x80, 0xb2, 0x83, 0x37, 0xe4, 0xe9, 0x43, 0x37, 0x2d, 0x7f, 0x8d,
	0x5a, 0xcf, 0x16, 0xf2, 0xd5, 0x05, 0x7d, 0x84, 0xaa, 0xec, 0x2e, 0xd9, 0x2d, 0xda, 0x67, 0xca,
	0xb7, 0xb5, 0xb7, 0xa0, 0xb7, 0x3e, 0x67, 0xa8, 0x7b, 0x56, 0x7c, 0x92, 0xa9, 0x9c, 0xe2, 0x93,
	0x72, 0xda, 0xa0, 0x25, 0x72, 0xa9, 0x5a, 0x5f, 0xc8, 0x83, 0x29, 0x80, 0xdd, 0xc5, 0x9c, 0xf5,
	0x19, 0xef, 0xa1, 0x9e, 0xbd, 0x2d, 0xf7, 0x69, 0x60, 0xee, 0x99, 0xba, 0x4f, 0x03, 0xf3, 0x4f,
	0x14, 0x2d, 0x5d, 0xd6, 0xe4, 0x1f, 0xd4, 0xfe, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x9c,
	0x08, 0x9a, 0x4f, 0x09, 0x00, 0x00,
}
